runtime: nodejs18
service: default

#automatic_scaling:
#  target_cpu_utilization: 0.9
#  min_instances: 1
#  max_instances: 2

env_variables:
  NEXT_PUBLIC_BASE_URL: "https://server-dot-mms-team-2.ue.r.appspot.com/api/v1"
  NEXT_PUBLIC_PUSHER_APP_KEY: "f6e2b78d4c39d6321a45"
