import "./globals.css";
import { GlobalContextProvider } from "../../Context/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalContextProvider>{children}</GlobalContextProvider>
    </html>
  );
}
