const UserActionTypes = {
  UPDATE_USER: "UPDATE_USER",
  UPDATE_PRIVACY_SETTINGS: "UPDATE_PRIVACY_SETTINGS",
  UPDATE_NOTIFICATION_SETTINGS: "UPDATE_NOTIFICATION_SETTINGS",
};

export default UserActionTypes;