#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm run precommit for mms-Admin frontend
cd frontend/mms-Admin
npm run precommit
#
## npm run precommit for mms-Admin backend
cd ../../backend
npm run build
